services:
  mas_nav_2027:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: mas_nav_image:latest  # 构建后的镜像名称
    container_name: mas_nav      # 固定容器名称，方便 VS Code 查找
    #restart: always              # 开机自启策略
    
    # 保持标准输入打开（防止 bash 退出）
    stdin_open: true
    # 分配一个伪终端
    tty: true

    # 网络、IPC、PID 设置
    network_mode: host
    ipc: host
    pid: host
    privileged: true

    # 环境变量
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    # 挂载配置
    volumes:
      # X11 显示挂载
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw

      # 代码挂载
      # 将当前目录挂载到容器内的 src
      - ./:/home/ros2_ws/src
      # 配置挂载：将 .vscode 目录映射到工作区根目录
      - ./.vscode:/home/ros2_ws/.vscode
      # 编译缓存挂载 (使用 Docker Volume)
      - ros2-build:/home/ros2_ws/build
      - ros2-install:/home/ros2_ws/install
      - ros2-log:/home/ros2_ws/log

volumes:
  ros2-build:
  ros2-install:
  ros2-log:
