/**:
  ros__parameters:
    mapping:
      # Output
      save_raw_mapping_frames: true
      output_root: "~/mapping"

      # Point range filter (imu_link frame). Set <= 0 to disable.
      cloud_range_min: 0.8 # Points out of this range will be filtered out (imu_link frame)
      cloud_range_max: 20.0 # Points out of this range will be filtered out (imu_link frame)

      # IMU refine optimization
      # refine IMU-rate trajectory using optimized odometry endpoints, then re-deskew keyframes using the refined trajectory
      enable_imu_refine: true
      imu_refine_max_iterations: 5

      # Keyframe selection (relative to last keyframe)
      keyframe_trans_thresh: 0.1 # meters
      keyframe_rot_thresh: 5.0 # degrees

      # Incremental map integration
      downsample_every_n_keyframes: 1000
      map_voxel_leaf_size: 0.05